images/images/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include("interface.urls"))
]

images/interface/urls.py
from django.urls import path

from . import views

app_name = "interface"
urlpatterns = [
    path("", views.index, name="index"),
	path("authenticate", views.log, name="log"),
	path("site", views.service, name="site"),
	path("page/<int:page_no>", views.page, name="page"),
	path("site/<int:img_id>", views.picture, name="picture"),
	path("edit/<int:img_id>", views.edit, name="edit"),
	path("edit/remove_rect/<int:rect_id>", views.remove_rect, name="rmv_rect"),
	path("edit/add", views.add_rect, name="add_rect"),
	path("page/filter/<int:page_no>", views.filter, name="filter"),
    path("edit/add_img", views.add_img, name="add_img")
]

images/interface/models.py
from django.db import models
import django.utils
from django.contrib.auth.models import User

import datetime

import django.utils.timesince
import django.utils.timezone

class Tag(models.Model):
    title = models.CharField(max_length=200, unique=True)
    def __str__(self) -> str:
        return str(self.title)

class Image(models.Model):
    title = models.CharField(max_length=200, unique=True)
    sizex = models.IntegerField()
    sizey = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    publication_date = models.DateTimeField(null=False, default=django.utils.timezone.now)
    description = models.CharField(null=True, max_length=1000)
    tags = models.ManyToManyField(Tag)
    def __str__(self) -> str:
        return self.title

class Rect(models.Model):
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    sizex = models.IntegerField()
    sizey = models.IntegerField()
    x = models.IntegerField()
    y = models.IntegerField()
    color = models.CharField(max_length=200, default='white')
    def __str__(self) -> str:
        return str(self.id)

images/interface/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views.defaults import page_not_found
from django.contrib.auth import authenticate
from django.urls import reverse
from django.core.paginator import Paginator
from .models import Image, Rect, Tag
from django.contrib.auth.models import User

# Create your views here.
def index(request):
	return render(request, "index.html", {})

def log(request):
	try:
		name = request.POST.get('username')
		password = request.POST.get('password')
	except KeyError:
		return HttpResponseRedirect(reverse('interface:index'))
	user = authenticate(request, username=name, password=password)
	if user == None:
		return HttpResponseRedirect(reverse('interface:index'))
	return render(request, "editor.html", {'user': user, 'image_set': user.image_set.all()})

def service(request):
	all_images = Image.objects.order_by('title')
	p = Paginator(all_images, 10)
	context = {
		'tags': Tag.objects.all(),
		'images': p.page(1).object_list,
		'site_no': 1,
		'next': 2,
		'prev': 0,
		'filtered': False
	}
	return render(request, "default.html", context)

def page(request, page_no):
	all_images = Image.objects.order_by('title')
	if len(all_images) < 10 * (page_no - 1) or page_no <= 0:
		return HttpResponse("page not found")
	if page_no == 1:
		return HttpResponseRedirect(reverse('interface:site'))
	p = Paginator(all_images, 10)
	context = {
		'tags': Tag.objects.all(),
		'images': p.page(page_no).object_list,
		'site_no': page_no,
		'next': page_no + 1,
		'prev': page_no - 1,
		'filtered': False
	}
	return render(request, "default.html", context)

def picture(request, img_id):
	image = get_object_or_404(Image, pk=img_id)
	context = {
		'image': image,
		'rect_set': image.rect_set.all()
	}
	return render(request, "picture.html", context)

def edit(request, img_id):
	user = request.POST.get('user')
	if user == None:
		return HttpResponseRedirect(reverse('interface:index'))
	image = get_object_or_404(Image, pk=img_id)
	rect_set = image.rect_set.all()
	context = {
		'user': user,
		'image': image,
		'rect_set': rect_set
	}
	return render(request, 'edit.html', context=context)

def remove_rect(request, rect_id):
	user = request.POST.get('user')
	image = request.POST.get('image')

	rect = get_object_or_404(Rect, pk = rect_id)
	image_proper = get_object_or_404(Image, title=image)

	if user != rect.image.user.username:
		return HttpResponse("remove not working")#HttpResponseRedirect(reverse('interface:index'))
	rect.delete()
	return render(request, 'edit.html', {'user': user, 'image': image_proper, 'rect_set': image_proper.rect_set.all()}) #TODO: redirect to edit

def add_rect(request):
	x, y, sizex, sizey = request.POST.get('x'), request.POST.get('y'), request.POST.get('sizex'), request.POST.get('sizey')
	image = request.POST.get('image')
	user = request.POST.get('user')
	color = request.POST.get('color')
	image_proper = get_object_or_404(Image, pk=image)
	if x == None or y == None or sizex == None or sizey == None or image == None or user == None:
		return HttpResponse("soething wrong with post")
	rect = Rect(x=x, y=y, sizex = sizex, sizey=sizey, image=image_proper, color=color)
	rect.save()
	return render(request, 'edit.html', {'user': user, 'image': image_proper, 'rect_set': image_proper.rect_set.all()})

def filter(request, page_no):
	tag_set = set()
	for tag in Tag.objects.all():
		if request.POST.get(tag.title) != None:
			tag_set.add(tag)
	sort = request.POST.get('sort')
	if len(tag_set) == 0 and sort == None:
		HttpResponseRedirect(reverse('interface:site')) #TODO: redirect to page or 404
	all_images = set()

	for tag in tag_set:
		all_images.update(tag.image_set.all())
	if len(all_images) < 10 * (page_no - 1) or page_no <= 0:
		return HttpResponse("page not found")
	
	img_list = list(all_images)
	img_list.sort(key =lambda a : a.title, reverse = (sort != None))
	p = Paginator(img_list, 10)
	
	context = {
		'tags': Tag.objects.all(),
		'filtered_tags': tag_set,
		'images': p.page(page_no).object_list,
		'site_no': page_no,
		'next': page_no + 1,
		'prev': page_no - 1,
		'sort': sort,
		'filtered': True
	}
	return render(request, "default.html", context)

def add_img(request):
	image_title = request.POST.get('image')
	username = request.POST.get('user')
	sizex = request.POST.get('sizex')
	sizey = request.POST.get('sizey')
	desc = request.POST.get('description')
	user = get_object_or_404(User, username=username)
	image, created = Image.objects.get_or_create(title=image_title, sizex=sizex, sizey=sizey, user=user, description=desc)
	if not created:
		return HttpResponse("Image already exists\n")
	image.save()
	return render(request, "editor.html", {'user': user, 'image_set': user.image_set.all()})

images/interface/templates/default.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
	{% for image in images %}
	#background{{ image.id }} {
            width: 100px;
            height: 100px;
			object-fit: scale-down;
            background-color: white;
            position: relative;
        }
	
    {% for rect in image.rect_set.all %}
        #object{{ rect.id }} {
            width: {% widthratio 100 image.sizex rect.sizex %}px;
            height: {% widthratio 100 image.sizex rect.sizey %}px;
            background-color: {{ rect.color }};
            object-fit: scale-down;
            position: absolute;
            left: {% widthratio 100 image.sizex rect.x %}px; 
            top: {% widthratio 100 image.sizex rect.y %}px;
        }
    {% endfor %}
	{% endfor %}
  </style>
  <title>HTML List</title>
</head>
<body>

<div class="grid grid-cols-3">
	<div class="col-span-1">
		<h2>tags</h2>
		<form action="{% url 'interface:filter' '1' %}" method="post">
			{% csrf_token %}
			{% for tag in tags %}
			<label> {{tag.title}} </label>
			<input type='checkbox' name="{{ tag.title }}"> <br>
			{% endfor %}
			<label> sort in increasing order </label>
			<input type='checkbox' name="sort"> <br>
			<button id='rect' name="filter" value="true"> submit </button> 
		</form>
	</div>
<div>
	<h1 class="text-xl">Images</h1><br>
	<ol class="list-decimal">
		{% for image in images %}
		<li>
			<p> {{ image.title }} </p>
		</li>
		<a href="{% url 'interface:picture' image.id %}">
		<div class='w-28 h-28 object-scale-down'>
			<svg width="100" height = "100">
				{% for rect in image.rect_set.all %}
				<rect x="{% widthratio 100 image.sizex rect.x %}" y="{% widthratio 100 image.sizex rect.y %}" width="{% widthratio 100 image.sizex rect.sizex %}" height="{% widthratio 100 image.sizex rect.sizey %}" fill="{{ rect.color }}"></rect>
				{% endfor %}
			</svg>
		</div>
	</a>
		{% endfor %}
		{% if not filtered %}
		<a href="{% url 'interface:page' next %}"> Next </a> <br>
		<a href="{% url 'interface:page' prev %}"> Previus </a>
		{% else %}
			<form action="{% url 'interface:filter' next %}" method="post">
				{% csrf_token %}
				{% for tag in filtered_tags %}
				<input type="hidden" name="{{ tag.title }}" value="true">
				{% endfor %}
				<button id='rect' name="filter" value="true"> next </button> 
			</form>
			<form action="{% url 'interface:filter' next %}" method="post">
				{% csrf_token %}
				{% for tag in filtered_tags %}
				<input type="hidden" name="{{ tag.title }}" value="true">
				{% endfor %}
				<button id='rect' name="filter" value="true"> prev </button> 
			</form>
		{% endif %}
	</ol>
</div>
<div></div>
</div>

</body>
</html>

images/interface/templates/default_filter.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
	{% for image in images %}
	#background{{ image.id }} {
            width: 100px;
            height: 100px;
			object-fit: scale-down;
            background-color: white;
            position: relative;
        }
	
    {% for rect in image.rect_set.all %}
        #object{{ rect.id }} {
            width: {% widthratio 100 image.sizex rect.sizex %}px;
            height: {% widthratio 100 image.sizex rect.sizey %}px;
            background-color: {{ rect.color }};
            object-fit: scale-down;
            position: absolute;
            left: {% widthratio 100 image.sizex rect.x %}px; 
            top: {% widthratio 100 image.sizex rect.y %}px;
        }
    {% endfor %}
	{% endfor %}
  </style>
  <title>HTML List</title>
</head>
<body>

<div class="grid grid-cols-3">
	<div class="col-span-1">
		<h2>tags</h2>
	</div>
<div>
	<h1 class="text-xl">Images</h1><br>
	<ol class="list-decimal">
		{% for image in images %}
		<li>
			<p> {{ image.title }} </p>
		</li>
		<a href="{% url 'interface:picture' image.id %}">
		<div class='w-28 h-28 object-scale-down'>
			<div id="background{{ image.id }}">
				{% for rect in image.rect_set.all %}
					<div id="object{{ rect.id }}"></div>
				{% endfor %}
			</div>
		</div>
	</a>
		{% endfor %}
		<a href="{% url 'interface:page' next %}"> Next </a> <br>
		<a href="{% url 'interface:page' prev %}"> Previus </a>
	</ol>
</div>
<div></div>
</div>

</body>
</html>

images/interface/templates/edit.html
<html>
 
<head>
    <title>To set position of an image</title>
    <style>
        
        #background {
            width: {{ image.sizex }};
            height: {{ image.sizey }};
            background-color: white;
            position: relative;
        }
        {% for rect in rect_set %}
        #object{{ rect.id }} {
            width: {{ rect.sizex }}px;
            height: {{ rect.sizey }}px;
            background-color: {{ rect.color }};
            object-fit: none;
            position: absolute;
            left: {{ rect.x }}px; 
            top: {{ rect.y }}px;
        }
        {% endfor %}
    </style>
</head>
 
<body>
    <h1> {{ image.title }} </h1>
    <svg width="{{ image.sizex }}" height = "{{ image.sizey }}" viewBox="0 0 {{ image.sizex }} {{ image.sizey }}">
        {% for rect in rect_set %}
        <rect x="{{ rect.x }}" y="{{ rect.y }}" width="{{ rect.sizex }}" height="{{ rect.sizey }}" fill="{{ rect.color }}"></rect>
        {% endfor %}
    </svg>
	<table>
		<tr>
			<th> x </th>
			<th> y </th>
			<th> size x </th>
			<th> size y </th>
			<th> color </th>
			<th>  </th>
		</tr>
		{% for rect in rect_set %}
		<tr>
			<td> {{ rect.x }} </td>
			<td> {{ rect.y }} </td>
			<td> {{ rect.sizex }} </td>
			<td> {{ rect.sizey }} </td>
			<td> {{ rect.color }} </td>
			<td>
				<form action="{% url 'interface:rmv_rect' rect.id %}" method="post">
					{% csrf_token %}
					<input type='hidden' id="image" name="image" value="{{ image.title }}">
					<button id='rect' name="user" value="{{ user }}"> remove </button> 
				</form>
			</td>
		</tr>
		{% endfor %}
	</table>
	<form action="{% url 'interface:add_rect' %}" method="post">
			{% csrf_token %}
			<label >color:</label><br>
			<input type="text" id="color" name="color" value="{{ color }}" required><br><br>

			<label>x:</label><br>
			<input type="number" id="x" name="x" value="{{ x }}" required><br><br>
			<label>y:</label><br>
			<input type="number" id="y" name="y" value="{{ y }}" required><br><br>
			<label>size x:</label><br>
			<input type="number" id="sizex" name="sizex" value="{{ sizex }}" required><br><br>
			<label>size y:</label><br>
			<input type="number" id="sizey" name="sizey" value="{{ sizey }}" required><br><br>
			<input type='hidden' id="user" name="user" value="{{ user }}">
			<button type="submit" id='image' name='image'  value={{ image.id }}> save </button>
	</form>

</body>
 
</html>

images/interface/templates/editor.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HTML List</title>
</head>
<body>

<h2> Add image </h2>
<form action="{% url 'interface:add_img' %}" method="post">
	{% csrf_token %}
	<label> title </label>
	<input type ='text' id='title' name='image' value='image title'><br><br>
	<input type="number" id="sizex" name="sizex" value="0" required><br><br>
	<input type="number" id="sizey" name="sizey" value="0" required><br><br>
	<input type="text" id="description" name="description" value=""><br><br>
	<button id='rect' id='submit' name="user" value="{{ user }}"> submit </button> 
</form>
<h2>Obrazki</h2>
<ol>
	{% for image in image_set %}
	<li> {{ image.title }}
	
	<form action="{% url 'interface:edit' image.id %}" method="post">
		{% csrf_token %}
		<button id='username' name="user" value={{ user }}> edit </button> 
	</form>

	</li>
	{% endfor %}
</ol>

</body>
</html>

images/interface/templates/index.html
<html>
<article>
	<form action="authenticate" method="post">
		{% csrf_token %}
		<label for="username">Username:</label><br>
        <input type="text" id="username" name="username" value="{{ username }}" required><br><br>

        <label for="password">Password:</label><br>
        <input type="password" id="password" name="password" value="{{ password }}" required><br><br>
		<input type="submit" value="log in">
	</form>
	<p><a href="{% url 'interface:site' %}">site</a></p>
</article>
</html>

images/interface/templates/picture.html
<html>
 
<head>
    <title>To set position of an image</title>
    <style>
        
        #background {
            width: {{ image.sizex }};
            height: {{ image.sizey }};
            background-color: white;
            position: relative;
        }
        {% for rect in rect_set %}
        #object{{ rect.id }} {
            width: {{ rect.sizex }}px;
            height: {{ rect.sizey }}px;
            background-color: {{ rect.color }};
            object-fit: none;
            position: absolute;
            left: {{ rect.x }}px; 
            top: {{ rect.y }}px;
        }
        {% endfor %}
    </style>
</head>
 
<body>
    <h1> {{ image.title }} </h1>
    <svg width="{{ image.sizex }}" height = "{{ image.sizey }}" viewBox="0 0 {{ image.sizex }} {{ image.sizey }}">
        {% for rect in rect_set %}
        <rect x="{{ rect.x }}" y="{{ rect.y }}" width="{{ rect.sizex }}" height="{{ rect.sizey }}" fill="{{ rect.color }}"></rect>
        {% endfor %}
    </svg>
    <h2> description </h2>
    <p> {{ image.description }} </p>
    <h2> Tags </h2>
    {% for tag in image.tags.all %}
    <p> {{tag.title}} </p>
    {% endfor %}
</body>
 
</html>